---
name: Validation

on:
  pull_request: {}
  push:
    branches:
      - main
      - feat/pre-commit

jobs:
  pre-commit:
    name: Pre-commit
    uses: fabasoad/reusable-workflows/.github/workflows/wf-pre-commit.yaml@feat/pre-commit
