---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

jobs:
  sast:
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@feat/security
