---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

jobs:
  security:
    name: Security
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security.yml@feat/security
