---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

jobs:
  sast:
    name: SAST
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/wf-security-sast.yml
    with:
      code-scanning: true
      sca: true
