---
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ref:
        description: ref (refs/heads/main)
        default: ${{ github.ref }}
        required: false
        type: string
      ref-name:
        description: ref_name (main)
        default: ${{ github.ref_name }}
        required: false
        type: string
      bump-tags:
        description: Whether to move semantic tags or not.
        default: true
        required: false
        type: boolean

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ inputs.ref }}"
      - name: Create release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ inputs.ref-name }}
          tag: ${{ inputs.ref-name }}
      - name: Bump tags
        if: inputs.bump-tags
        uses: fischerscode/tagger@v0
        with:
          prefix: v
