---
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      bump-tags:
        description: Whether to move semantic tags or not.
        default: true
        required: false
        type: boolean

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        uses: softprops/action-gh-release@v2
      - name: Bump tags
        if: inputs.bump-tags
        uses: fischerscode/tagger@v0
        with:
          prefix: v
