---
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      install-command:
        description: Command that installs dependencies
        required: false
        default: "make install"
        type: string
      test-command:
        description: Command that runs tests
        required: false
        default: "make test"
        type: string
      python-version-file:
        description: |
          File containing the version Spec of the version to use. Examples:
          pyproject.toml, .python-version, .tool-versions.
        required: false
        default: "pyproject.toml"
        type: string

defaults:
  run:
    shell: sh

jobs:
  unit-tests-all:
    name: All
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          persist-credentials: "false"

      - name: Prepare metadata
        id: metadata
        run: | # pragma: allowlist secret
          if [ -f "uv.lock" ]; then
            package_manager="uv"
            cache_dependency_path="uv.lock"
          elif [ -f "poetry.lock" ]; then
            package_manager="poetry"
            cache_dependency_path="poetry.lock"
          elif [ -f "Pipfile.lock" ]; then
            package_manager="pipenv"
            cache_dependency_path="Pipfile.lock"
          else
            echo "No lock file found."
            exit 1
          fi
          echo "package-manager=${package_manager}" >> "$GITHUB_OUTPUT"
          echo "cache-dependency-path=${cache_dependency_path}" >> "$GITHUB_OUTPUT"

      - name: Setup uv
        if: steps.metadata.outputs.package-manager == 'uv'
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: "true"
          version-file: "${{ inputs.python-version-file }}"

      - name: Setup Poetry
        if: steps.metadata.outputs.package-manager == 'poetry'
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "${{ inputs.python-version-file }}"
          cache: "${{ case(steps.metadata.outputs.package-manager == 'uv', '', steps.metadata.outputs.package-manager) }}"
          cache-dependency-path: "${{ case(steps.metadata.outputs.package-manager == 'uv', '', steps.metadata.outputs.cache-dependency-path) }}"

      - name: Setup pipenv
        if: steps.metadata.outputs.package-manager == 'pipenv'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Install dependencies
        env:
          INPUT_INSTALL_COMMAND: "${{ inputs.install-command }}"
        run: ${INPUT_INSTALL_COMMAND}

      - name: Run tests
        env:
          INPUT_TEST_COMMAND: "${{ inputs.test-command }}"
        run: ${INPUT_TEST_COMMAND}
