---
name: Pre-commit

on:
  workflow_call:
    inputs:
      target-branch:
        description: |
          Target branch name in front of which you want to validate changed files,
          e.g. main
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      pre-commit-config-path:
        description: "Path to pre-commit config file"
        required: false
        default: ".pre-commit-config.yaml"
        type: string
      run-on-all-files:
        description: "Whether to run on all files or not"
        required: false
        default: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        type: boolean
      run-on-changed-files:
        description: "Whether to run on changed files or not"
        required: false
        default: ${{ github.event_name == 'pull_request' }}
        type: boolean
      skip-hooks:
        description: "Comma-separated list of hooks to skip"
        required: false
        default: "no-commit-to-branch"
        type: string

defaults:
  run:
    shell: sh

jobs:
  pre-commit:
    name: ${{ inputs.run-on-all-files && 'All files' || 'Changed files' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fabasoad/pre-commit-container:latest
    env:
      SKIP: ${{ inputs.skip-hooks }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update git config
        run: git config --global --add safe.directory "$(pwd)"
      - name: Run pre-commit on changed files
        if: ${{ inputs.run-on-changed-files }}
        env:
          INPUT_PRE_COMMIT_CONFIG_PATH: ${{ inputs.pre-commit-config-path }}
          INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        run: |
          pre-commit run --config "${INPUT_PRE_COMMIT_CONFIG_PATH}" --from-ref "origin/${INPUT_TARGET_BRANCH}" --to-ref "${GITHUB_SHA}" --hook-stage commit
          pre-commit run --config "${INPUT_PRE_COMMIT_CONFIG_PATH}" --from-ref "origin/${INPUT_TARGET_BRANCH}" --to-ref "${GITHUB_SHA}" --hook-stage push
      - name: Run pre-commit on all files
        if: ${{ inputs.run-on-all-files }}
        env:
          INPUT_PRE_COMMIT_CONFIG_PATH: ${{ inputs.pre-commit-config-path }}
        run: |
          pre-commit run --config "${INPUT_PRE_COMMIT_CONFIG_PATH}" --all-files --hook-stage commit
          pre-commit run --config "${INPUT_PRE_COMMIT_CONFIG_PATH}" --all-files --hook-stage push
