---
name: Labels

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      github-token:
        description: |
          GitHub token used to fetch the repository and update LICENSE file.
        required: false
        default: ${{ github.token }}
        type: string

jobs:
  label-syncer:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.github-token }}
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
