---
name: Labels

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      github-token:
        description: |
          GitHub token used to fetch the repository and update LICENSE file.
        required: true

jobs:
  label-syncer:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.github-token }}"
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: "${{ secrets.github-token }}"
