---
name: Security

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      sast-run:
        description: Whether to run SAST or not. Defaults to true.
        required: false
        default: true
        type: boolean
      sast-languages:
        description: A comma-separated list of CodeQL languages to analyze.
        required: false
        default: "javascript"
        type: string
      sast-path:
        description: Path to the directory for SAST.
        required: false
        default: "."
        type: string
      sca-run:
        description: Whether to run SCA or not. Defaults to true.
        required: false
        default: true
        type: boolean
      sca-path:
        description: Path to the directory for SCA.
        required: false
        default: "."
        type: string
      dast-run:
        description: Whether to run DAST or not. Defaults to true.
        required: false
        default: false
        type: boolean
      dast-target-url:
        description: Target URL to perform DAST analysis.
        required: false
        default: ""
        type: string
      ghas-category:
        description: String used by GHAS for matching analyses.
        required: false
        default: "default"
        type: string

jobs:
  sast:
    name: SAST
    if: inputs.sast-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "${{ inputs.sast-languages }}"
      - name: Perform CodeQL Analysis
        id: codeql-analysis
        uses: github/codeql-action/analyze@v3
      - name: Upload to GHAS
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: "sast-${{ inputs.ghas-category }}"
          sarif_file: "${{ steps.codeql-analysis.outputs.sarif-output }}"
  sca:
    name: SCA
    if: inputs.sca-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Scan  project
        id: sca
        uses: anchore/scan-action@v3
        with:
          by-cve: "true"
          path: "${{ inputs.sca-path }}"
      - name: Upload to GHAS
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: "sca-${{ inputs.ghas-category }}"
          sarif_file: "${{ steps.sca.outputs.sarif }}"
  nuclei:
    name: Nuclei
    if: inputs.dast-run && inputs.dast-target-url != ''
    runs-on: ubuntu-latest
    steps:
      - name: Perform scanning
        uses: projectdiscovery/nuclei-action@v2.0.1
        with:
          target: "${{ inputs.dast-target-url }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log
      - name: Upload to GHAS
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: "nuclei-${{ inputs.ghas-category }}"
          sarif_file: nuclei.sarif
  zap:
    name: ZAP
    if: inputs.dast-run && inputs.dast-target-url != ''
    runs-on: ubuntu-latest
    container:
      image: zaproxy/zap-stable:2.14.0
      options: --user root
    steps:
      - name: Perform scanning
        env:
          INPUT_DAST_TARGET_URL: "${{ inputs.dast-target-url }}"
        run: zap-baseline.py -t "${INPUT_DAST_TARGET_URL}" -J zap-output.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-output.json
          path: zap-output.json
