---
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      manifest-file-ref:
        description: |
          reusable-workflows repository branch name from where you want to use
          labels.yml manifest file.
        required: false
        default: "main"
        type: string

jobs:
  label-syncer:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Download manifest file
        run: |
          path="${GITHUB_WORKSPACE}/.github/labels.yml"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -o "${path}" \
            "https://raw.githubusercontent.com/fabasoad/reusable-workflows/${{ inputs.manifest-file-ref }}/.github/labels.yml"
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
