---
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      manifest-file-ref:
        description: |
          reusable-workflows repository branch name from where you want to use
          labels.yml manifest file.
        required: false
        default: "main"
        type: string

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Download manifest file
        run: |
          path="${GITHUB_WORKSPACE}/.github/labels.yml"
          curl -H "Authorization: token ${{ github.token }}" \
            -o "${path}" \
            "https://raw.githubusercontent.com/fabasoad/reusable-workflows/${{ inputs.manifest-file-ref }}/.github/labels.yml"
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        with:
          token: "${{ github.token }}"
